version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: robot-app
    ports:
      - "5001:5001"
    restart: always
    depends_on:
      - database
  database:
    image: postgres:14
    container_name: database
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=robot-app
      - TZ=Asia/Ho_Chi_Minh